// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOgwQhypLcSNVb9kbjNsaMivC5Qo4PUWs',
    appId: '1:1044782632175:web:a6b7f8f2f01ee621f3df1a',
    messagingSenderId: '1044782632175',
    projectId: 'lpmimanage-a057b',
    authDomain: 'lpmimanage-a057b.firebaseapp.com',
    storageBucket: 'lpmimanage-a057b.firebasestorage.app',
    measurementId: 'G-5X8BDRSBGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQGmfMYgpjSUBFwKjl09_TKWXiIhV7pOE',
    appId: '1:1044782632175:android:f2692894bf78ee73f3df1a',
    messagingSenderId: '1044782632175',
    projectId: 'lpmimanage-a057b',
    storageBucket: 'lpmimanage-a057b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa_hP3lwsp4VelxddGXVga1hp5JxhdM6Y',
    appId: '1:1044782632175:ios:dd76c2edfe8ef155f3df1a',
    messagingSenderId: '1044782632175',
    projectId: 'lpmimanage-a057b',
    storageBucket: 'lpmimanage-a057b.firebasestorage.app',
    iosBundleId: 'com.example.lpmiManage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa_hP3lwsp4VelxddGXVga1hp5JxhdM6Y',
    appId: '1:1044782632175:ios:dd76c2edfe8ef155f3df1a',
    messagingSenderId: '1044782632175',
    projectId: 'lpmimanage-a057b',
    storageBucket: 'lpmimanage-a057b.firebasestorage.app',
    iosBundleId: 'com.example.lpmiManage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOgwQhypLcSNVb9kbjNsaMivC5Qo4PUWs',
    appId: '1:1044782632175:web:811873f0bc146871f3df1a',
    messagingSenderId: '1044782632175',
    projectId: 'lpmimanage-a057b',
    authDomain: 'lpmimanage-a057b.firebaseapp.com',
    storageBucket: 'lpmimanage-a057b.firebasestorage.app',
    measurementId: 'G-42878DP255',
  );
}
